/* Generated by Yosys 0.52+117 (git sha1 11f234824, c++ 16.0.0 -fPIC -O3) */

(* pipeline_depth = 32'd3 *)
(* architecture = "xilinx-ultrascale-plus" *)
(* template = "dsp" *)
(* use_dsp = "yes" *)
(* top =  1  *)
(* src = "sub_mul.sv:7.1-31.10" *)
module sub_mul(clk, a, b, d, out);
  (* force_downto = 32'd1 *)
  (* src = "sub_mul.sv:24.15-24.20|/Users/gussmith/.local/bin/../share/yosys/xilinx/arith_map.v:116.23-116.25" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16" *)
  wire [16:0] _000_;
  (* force_downto = 32'd1 *)
  (* src = "sub_mul.sv:24.15-24.20|/Users/gussmith/.local/bin/../share/yosys/xilinx/arith_map.v:112.23-112.24" *)
  wire [16:0] _001_;
  (* force_downto = 32'd1 *)
  (* src = "sub_mul.sv:24.15-24.20|/Users/gussmith/.local/bin/../share/yosys/xilinx/arith_map.v:112.26-112.27" *)
  wire [16:0] _002_;
  (* force_downto = 32'd1 *)
  (* src = "sub_mul.sv:24.15-24.20|/Users/gussmith/.local/bin/../share/yosys/xilinx/arith_map.v:170.23-170.24" *)
  (* unused_bits = "0 1 2 4 5 6 8 9 10 12 13 14 16 17 18 19" *)
  wire [19:0] _003_;
  (* force_downto = 32'd1 *)
  (* src = "sub_mul.sv:24.15-24.20|/Users/gussmith/.local/bin/../share/yosys/xilinx/arith_map.v:168.23-168.24" *)
  (* unused_bits = "17 18 19" *)
  wire [19:0] _004_;
  wire _005_;
  wire [15:0] _006_;
  wire _007_;
  (* force_downto = 32'd1 *)
  (* src = "sub_mul.sv:24.14-24.25|/Users/gussmith/.local/bin/../share/yosys/mul2dsp.v:91.5-95.4|/Users/gussmith/.local/bin/../share/yosys/mul2dsp.v:65.23-65.24" *)
  wire [15:0] _008_;
  (* src = "sub_mul.sv:24.14-24.25|/Users/gussmith/.local/bin/../share/yosys/mul2dsp.v:91.5-95.4|/Users/gussmith/.local/bin/../share/yosys/mul2dsp.v:148.7-152.6|/Users/gussmith/.local/bin/../share/yosys/mul2dsp.v:253.6-257.5|/Users/gussmith/.local/bin/../share/yosys/xilinx/xcu_dsp_map.v:8.14-8.18" *)
  (* unused_bits = "16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47" *)
  wire [47:0] _009_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _010_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _011_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _012_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _013_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _014_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _015_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _016_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _017_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _018_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _019_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _020_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _021_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _022_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _023_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _024_;
  (* force_downto = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:30.21-30.22" *)
  wire [1:0] _025_;
  (* data = 32'd1 *)
  (* src = "sub_mul.sv:12.16-12.17" *)
  input [15:0] a;
  wire [15:0] a;
  (* data = 32'd1 *)
  (* src = "sub_mul.sv:14.16-14.17" *)
  input [15:0] b;
  wire [15:0] b;
  (* clk = 32'd1 *)
  (* src = "sub_mul.sv:10.9-10.12" *)
  input clk;
  wire clk;
  (* data = 32'd1 *)
  (* src = "sub_mul.sv:16.16-16.17" *)
  input [15:0] d;
  wire [15:0] d;
  (* out = 32'd1 *)
  (* src = "sub_mul.sv:18.16-18.19" *)
  output [15:0] out;
  wire [15:0] out;
  (* src = "sub_mul.sv:21.23-21.29" *)
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15" *)
  wire [31:0] stage1;
  (* src = "sub_mul.sv:21.31-21.37" *)
  wire [31:0] stage2;
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _026_ (
    .I0(_025_[0]),
    .I1(_025_[1]),
    .O(_001_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _027_ (
    .I0(_024_[0]),
    .I1(_024_[1]),
    .O(_001_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _028_ (
    .I0(_023_[0]),
    .I1(_023_[1]),
    .O(_001_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _029_ (
    .I0(_022_[0]),
    .I1(_022_[1]),
    .O(_001_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _030_ (
    .I0(_019_[0]),
    .I1(_019_[1]),
    .O(_001_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _031_ (
    .I0(_017_[0]),
    .I1(_017_[1]),
    .O(_001_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _032_ (
    .I0(_015_[0]),
    .I1(_015_[1]),
    .O(_001_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _033_ (
    .I0(_014_[0]),
    .I1(_014_[1]),
    .O(_001_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _034_ (
    .I0(_013_[0]),
    .I1(_013_[1]),
    .O(_001_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _035_ (
    .I0(_012_[0]),
    .I1(_012_[1]),
    .O(_001_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _036_ (
    .I0(_011_[0]),
    .I1(_011_[1]),
    .O(_001_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _037_ (
    .I0(_010_[0]),
    .I1(_010_[1]),
    .O(_001_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _038_ (
    .I0(_020_[0]),
    .I1(_020_[1]),
    .O(_001_[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _039_ (
    .I0(_018_[0]),
    .I1(_018_[1]),
    .O(_001_[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _040_ (
    .I0(_016_[0]),
    .I1(_016_[1]),
    .O(_001_[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/lut_map.v:43.26-44.30" *)
  LUT2 #(
    .INIT(4'h9)
  ) _041_ (
    .I0(_021_[0]),
    .I1(_021_[1]),
    .O(_001_[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sub_mul.sv:24.15-24.20|/Users/gussmith/.local/bin/../share/yosys/xilinx/arith_map.v:176.11-184.5" *)
  CARRY4 _042_ (
    .CI(1'h0),
    .CO(_000_[3:0]),
    .CYINIT(1'h1),
    .DI({ _022_[1], _023_[1], _024_[1], _025_[1] }),
    .O(_002_[3:0]),
    .S(_001_[3:0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sub_mul.sv:24.15-24.20|/Users/gussmith/.local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _043_ (
    .CI(_000_[3]),
    .CO(_000_[7:4]),
    .CYINIT(1'h0),
    .DI({ _014_[1], _015_[1], _017_[1], _019_[1] }),
    .O(_002_[7:4]),
    .S(_001_[7:4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sub_mul.sv:24.15-24.20|/Users/gussmith/.local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _044_ (
    .CI(_000_[7]),
    .CO(_000_[11:8]),
    .CYINIT(1'h0),
    .DI({ _010_[1], _011_[1], _012_[1], _013_[1] }),
    .O(_002_[11:8]),
    .S(_001_[11:8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sub_mul.sv:24.15-24.20|/Users/gussmith/.local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _045_ (
    .CI(_000_[11]),
    .CO(_000_[15:12]),
    .CYINIT(1'h0),
    .DI({ _021_[1], _016_[1], _018_[1], _020_[1] }),
    .O(_002_[15:12]),
    .S(_001_[15:12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sub_mul.sv:24.15-24.20|/Users/gussmith/.local/bin/../share/yosys/xilinx/arith_map.v:186.14-194.8" *)
  CARRY4 _046_ (
    .CI(_000_[15]),
    .CO({ _003_[19:17], _000_[16] }),
    .CYINIT(1'h0),
    .DI(4'h0),
    .O({ _004_[19:17], _002_[16] }),
    .S(4'h1)
  );
  BUFG _047_ (
    .I(_005_),
    .O(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _048_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[0]),
    .Q(stage2[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _049_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[1]),
    .Q(stage2[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _050_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[2]),
    .Q(stage2[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _051_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[3]),
    .Q(stage2[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _052_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[4]),
    .Q(stage2[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _053_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[5]),
    .Q(stage2[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _054_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[6]),
    .Q(stage2[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _055_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[7]),
    .Q(stage2[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _056_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[8]),
    .Q(stage2[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _057_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[9]),
    .Q(stage2[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _058_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[10]),
    .Q(stage2[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _059_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[11]),
    .Q(stage2[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _060_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[12]),
    .Q(stage2[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _061_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[13]),
    .Q(stage2[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _062_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[14]),
    .Q(stage2[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/gussmith/.local/bin/../share/yosys/xilinx/cells_map.v:65.61-65.155" *)
  SRL16E #(
    .INIT(3'h0),
    .IS_CLK_INVERTED(1'h0)
  ) _063_ (
    .A0(1'h0),
    .A1(1'h1),
    .A2(1'h0),
    .A3(1'h0),
    .CE(1'h1),
    .CLK(_007_),
    .D(_008_[15]),
    .Q(stage2[15])
  );
  (* keep = 32'd1 *)
  IBUF _064_ (
    .I(a[0]),
    .O(_025_[0])
  );
  (* keep = 32'd1 *)
  IBUF _065_ (
    .I(a[1]),
    .O(_024_[0])
  );
  (* keep = 32'd1 *)
  IBUF _066_ (
    .I(a[10]),
    .O(_011_[0])
  );
  (* keep = 32'd1 *)
  IBUF _067_ (
    .I(a[11]),
    .O(_010_[0])
  );
  (* keep = 32'd1 *)
  IBUF _068_ (
    .I(a[12]),
    .O(_020_[0])
  );
  (* keep = 32'd1 *)
  IBUF _069_ (
    .I(a[13]),
    .O(_018_[0])
  );
  (* keep = 32'd1 *)
  IBUF _070_ (
    .I(a[14]),
    .O(_016_[0])
  );
  (* keep = 32'd1 *)
  IBUF _071_ (
    .I(a[15]),
    .O(_021_[0])
  );
  (* keep = 32'd1 *)
  IBUF _072_ (
    .I(a[2]),
    .O(_023_[0])
  );
  (* keep = 32'd1 *)
  IBUF _073_ (
    .I(a[3]),
    .O(_022_[0])
  );
  (* keep = 32'd1 *)
  IBUF _074_ (
    .I(a[4]),
    .O(_019_[0])
  );
  (* keep = 32'd1 *)
  IBUF _075_ (
    .I(a[5]),
    .O(_017_[0])
  );
  (* keep = 32'd1 *)
  IBUF _076_ (
    .I(a[6]),
    .O(_015_[0])
  );
  (* keep = 32'd1 *)
  IBUF _077_ (
    .I(a[7]),
    .O(_014_[0])
  );
  (* keep = 32'd1 *)
  IBUF _078_ (
    .I(a[8]),
    .O(_013_[0])
  );
  (* keep = 32'd1 *)
  IBUF _079_ (
    .I(a[9]),
    .O(_012_[0])
  );
  (* keep = 32'd1 *)
  IBUF _080_ (
    .I(b[0]),
    .O(_006_[0])
  );
  (* keep = 32'd1 *)
  IBUF _081_ (
    .I(b[1]),
    .O(_006_[1])
  );
  (* keep = 32'd1 *)
  IBUF _082_ (
    .I(b[10]),
    .O(_006_[10])
  );
  (* keep = 32'd1 *)
  IBUF _083_ (
    .I(b[11]),
    .O(_006_[11])
  );
  (* keep = 32'd1 *)
  IBUF _084_ (
    .I(b[12]),
    .O(_006_[12])
  );
  (* keep = 32'd1 *)
  IBUF _085_ (
    .I(b[13]),
    .O(_006_[13])
  );
  (* keep = 32'd1 *)
  IBUF _086_ (
    .I(b[14]),
    .O(_006_[14])
  );
  (* keep = 32'd1 *)
  IBUF _087_ (
    .I(b[15]),
    .O(_006_[15])
  );
  (* keep = 32'd1 *)
  IBUF _088_ (
    .I(b[2]),
    .O(_006_[2])
  );
  (* keep = 32'd1 *)
  IBUF _089_ (
    .I(b[3]),
    .O(_006_[3])
  );
  (* keep = 32'd1 *)
  IBUF _090_ (
    .I(b[4]),
    .O(_006_[4])
  );
  (* keep = 32'd1 *)
  IBUF _091_ (
    .I(b[5]),
    .O(_006_[5])
  );
  (* keep = 32'd1 *)
  IBUF _092_ (
    .I(b[6]),
    .O(_006_[6])
  );
  (* keep = 32'd1 *)
  IBUF _093_ (
    .I(b[7]),
    .O(_006_[7])
  );
  (* keep = 32'd1 *)
  IBUF _094_ (
    .I(b[8]),
    .O(_006_[8])
  );
  (* keep = 32'd1 *)
  IBUF _095_ (
    .I(b[9]),
    .O(_006_[9])
  );
  (* keep = 32'd1 *)
  IBUF _096_ (
    .I(clk),
    .O(_005_)
  );
  (* keep = 32'd1 *)
  IBUF _097_ (
    .I(d[0]),
    .O(_025_[1])
  );
  (* keep = 32'd1 *)
  IBUF _098_ (
    .I(d[1]),
    .O(_024_[1])
  );
  (* keep = 32'd1 *)
  IBUF _099_ (
    .I(d[10]),
    .O(_011_[1])
  );
  (* keep = 32'd1 *)
  IBUF _100_ (
    .I(d[11]),
    .O(_010_[1])
  );
  (* keep = 32'd1 *)
  IBUF _101_ (
    .I(d[12]),
    .O(_020_[1])
  );
  (* keep = 32'd1 *)
  IBUF _102_ (
    .I(d[13]),
    .O(_018_[1])
  );
  (* keep = 32'd1 *)
  IBUF _103_ (
    .I(d[14]),
    .O(_016_[1])
  );
  (* keep = 32'd1 *)
  IBUF _104_ (
    .I(d[15]),
    .O(_021_[1])
  );
  (* keep = 32'd1 *)
  IBUF _105_ (
    .I(d[2]),
    .O(_023_[1])
  );
  (* keep = 32'd1 *)
  IBUF _106_ (
    .I(d[3]),
    .O(_022_[1])
  );
  (* keep = 32'd1 *)
  IBUF _107_ (
    .I(d[4]),
    .O(_019_[1])
  );
  (* keep = 32'd1 *)
  IBUF _108_ (
    .I(d[5]),
    .O(_017_[1])
  );
  (* keep = 32'd1 *)
  IBUF _109_ (
    .I(d[6]),
    .O(_015_[1])
  );
  (* keep = 32'd1 *)
  IBUF _110_ (
    .I(d[7]),
    .O(_014_[1])
  );
  (* keep = 32'd1 *)
  IBUF _111_ (
    .I(d[8]),
    .O(_013_[1])
  );
  (* keep = 32'd1 *)
  IBUF _112_ (
    .I(d[9]),
    .O(_012_[1])
  );
  (* keep = 32'd1 *)
  OBUF _113_ (
    .I(stage2[0]),
    .O(out[0])
  );
  (* keep = 32'd1 *)
  OBUF _114_ (
    .I(stage2[1]),
    .O(out[1])
  );
  (* keep = 32'd1 *)
  OBUF _115_ (
    .I(stage2[10]),
    .O(out[10])
  );
  (* keep = 32'd1 *)
  OBUF _116_ (
    .I(stage2[11]),
    .O(out[11])
  );
  (* keep = 32'd1 *)
  OBUF _117_ (
    .I(stage2[12]),
    .O(out[12])
  );
  (* keep = 32'd1 *)
  OBUF _118_ (
    .I(stage2[13]),
    .O(out[13])
  );
  (* keep = 32'd1 *)
  OBUF _119_ (
    .I(stage2[14]),
    .O(out[14])
  );
  (* keep = 32'd1 *)
  OBUF _120_ (
    .I(stage2[15]),
    .O(out[15])
  );
  (* keep = 32'd1 *)
  OBUF _121_ (
    .I(stage2[2]),
    .O(out[2])
  );
  (* keep = 32'd1 *)
  OBUF _122_ (
    .I(stage2[3]),
    .O(out[3])
  );
  (* keep = 32'd1 *)
  OBUF _123_ (
    .I(stage2[4]),
    .O(out[4])
  );
  (* keep = 32'd1 *)
  OBUF _124_ (
    .I(stage2[5]),
    .O(out[5])
  );
  (* keep = 32'd1 *)
  OBUF _125_ (
    .I(stage2[6]),
    .O(out[6])
  );
  (* keep = 32'd1 *)
  OBUF _126_ (
    .I(stage2[7]),
    .O(out[7])
  );
  (* keep = 32'd1 *)
  OBUF _127_ (
    .I(stage2[8]),
    .O(out[8])
  );
  (* keep = 32'd1 *)
  OBUF _128_ (
    .I(stage2[9]),
    .O(out[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "sub_mul.sv:24.14-24.25|/Users/gussmith/.local/bin/../share/yosys/mul2dsp.v:91.5-95.4|/Users/gussmith/.local/bin/../share/yosys/mul2dsp.v:148.7-152.6|/Users/gussmith/.local/bin/../share/yosys/mul2dsp.v:253.6-257.5|/Users/gussmith/.local/bin/../share/yosys/xilinx/xcu_dsp_map.v:31.4-48.3" *)
  DSP48E2 #(
    .ACASCREG(32'sd0),
    .ADREG(32'sd0),
    .ALUMODEREG(32'sd0),
    .AMULTSEL("A"),
    .AREG(32'sd0),
    .A_INPUT("DIRECT"),
    .BCASCREG(32'sd0),
    .BMULTSEL("B"),
    .BREG(32'sd0),
    .B_INPUT("DIRECT"),
    .CARRYINREG(32'sd0),
    .CARRYINSELREG(32'sd0),
    .CREG(32'sd0),
    .DREG(32'sd0),
    .INMODEREG(32'sd0),
    .MREG(32'sd0),
    .OPMODEREG(32'sd0),
    .PREG(32'sd0),
    .USE_MULT("MULTIPLY"),
    .USE_SIMD("ONE48")
  ) _129_ (
    .A({ 13'h0000, _002_ }),
    .ACIN(30'h00000000),
    .ALUMODE(4'h0),
    .B({ 2'h0, _006_ }),
    .BCIN(18'h00000),
    .C(48'h000000000000),
    .CARRYIN(1'h0),
    .CARRYINSEL(3'h0),
    .D(27'h0000000),
    .INMODE(5'h00),
    .OPMODE(9'h005),
    .P({ _009_[47:16], _008_ }),
    .PCIN(48'h000000000000)
  );
  assign _001_[16] = 1'h1;
  assign _003_[16:0] = _000_;
  assign _004_[16:0] = _002_;
  assign _009_[15:0] = _008_;
  assign stage1[31:16] = 16'hxxxx;
  assign stage2[31:16] = 16'hxxxx;
endmodule
